### ISSUE TITLE
Secure credential storage failed to load.

### ISSUE THREAD

**Issue by Brodan** [twilio/twilio-cli#135]
#### Issue Summary

Sorry to be coming at ya'll with more bugs, this is a follow-up to my last issue (#134) which was fixed in the release from yesterday. Seems like the API Keys are now being created properly but now they can't be stored.

#### Steps to Reproduce

1. `twilio login`
2. follow prompts, enter identifier for profile, account sid, auth token, etc...
3. see error

#### Technical details:

* `twilio version` output: `twilio-cli/1.8.0 darwin-x64 node-v10.16.0`
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
[DEBUG] Failed to find the keytar module with the CLI: Cannot find module 'keytar'
[DEBUG] Failed to find the keytar module anywhere: Cannot find module 'keytar'
 » Secure credential storage failed to load.
```

It should be noted that up until that point the API keys do seem to be created now, and I can find them in my Twilio console (https://www.twilio.com/console/project/api-keys), they just aren't being

**Comment by Brodan** [comment]
Should be noted that after cloning the repo and running `npm install` locally I was able to `twilio login` fine. Seems like somewhere in the original install or during a brew update `keytar`never got installed?

**Comment by childish-sambino** [comment]
Yup, `keytar` was not getting bundled with the brew install due to a change in the release process. That has been resolved in the `1.8.1` release.

Currently looking into more reliable ways of including `keytar`: https://github.com/twilio/twilio-cli/issues/119

**Comment by oervamate** [comment]
@childish-sambino , it looks like that `twilio login` is working in `twilio-cli/2.17.0 win32-x64 node-v12.18.3`, but doesn't work in `twilio-cli/2.20.0 wsl-x64 node-v14.16.0`. Maybe something related to WSL? 

Is there a turnaround solution for multiple profiles with .env files? I need to deploy in both development and production environments.

**Comment by kridai** [comment]
Thanks for reaching out @sagitarious12 . Typically when we do `twilio login`, `twilio profiles:create`,  the credentials are stored in keyring. (Currently WSL2 doesn't provide support to run Linux GUI applications including the prompt in the GUI which is asked to unlock the keyring), I do see a support coming, which is currently in [preview](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps).
Meanwhile there are few alternatives

- [one workaround is unlocking the gnome keyring with password supplied via stdin](https://keyring.readthedocs.io/en/latest/#using-keyring-on-headless-linux-systems)
- [other option is you can use env vars to store/access credentials](https://www.twilio.com/docs/twilio-cli/general-usage#want-to-use-environment-variables-instead-of-creating-a-profile). Here you could only store one profile at a time.
